package-lock.json, package.json, src/runtime/web/localstorage.js
When app is loaded in iFrame in Chrome incognito mode iFrame does not allow to access window as third party access is block in chrome incognito anonymous mode.
=> iframe window local storage

webpack/webpack.web.js
=> fix: fixed esm issue

CHANGELOG.md, package-lock.json, package.json
- v3.18.1
- updated CHANGELOG.md
=> fix: updated package files and CHANGELOG.md

src/lib/content-type.ts, src/lib/query.ts, test/api/contenttype.spec.ts, test/unit/contenttype.spec.ts
containedIn query implementation with api and unit test case
=> Feat/cs 43910 containedIn query implementation

package-lock.json, package.json, sanity-report.js
- Basic sanity optimisation
- Slack notification with test report and summary
=> Basic sanity optimization

CHANGELOG.md, package-lock.json, package.json, sanity-report.js
updated package files and changeLog
=> chore: :package: updated package files and changeLog

src/lib/query.ts, test/api/entry-queryables.spec.ts, test/unit/entry-queryable.spec.ts
notEqual to query operator implementation and test cases
=> feat: notEqual to query operator

CHANGELOG.md, package-lock.json, package.json
=> typescript version bump

.github/workflows/npm-publish.yml
changed tag to latest in npm workflow
=> fix: changed tag to latest in npm workflow

test/index.js, test/live-preview/live-preview-test.js
=> live preview sanity test

CHANGELOG.md, package-lock.json, package.json
slack bolt to dev dependencies
=> hotfix for moving slack/bolt to devDependencies

CHANGELOG.md, package-lock.json, package.json, src/lib/base-query.ts, src/lib/entries.ts, src/lib/internal-types.ts, src/lib/pagination.ts, src/lib/query.ts, src/lib/taxonomy-query.ts, test/unit/query.spec.ts
query params and parameters to be carry forwarded to query
=> fix: parameters and query params in query class

CHANGELOG.md, package-lock.json, package.json, src/core/lib/request.js
- Removed encode for query params
- version bump to 3.20.3
=> Hotfix | 02-08-2024

CHANGELOG.md, package-lock.json, package.json, sanity-report.js
- version bump to 3.20.4
- Fix file upload function in sanity report file
=> dx 1042 remove secrets gocd piplines

README.md
included subresource integrity attribute
=> dx | 1393 sre issue

CHANGELOG.md, package-lock.json, package.json, src/core/lib/utils.js
- Handle empty entries in case of Live Preview with proper error message
- version bump 3.22.1 -> 3.22.2
- updated ReadMe and package files
=> dx | 1675 handle empty entries

package-lock.json, package.json, src/runtime/node/http.js, src/runtime/web/http.js
- dropped isomorphic fetch and node fetch
- version bump to 3.23.1
- sanity check needs to be done once @sunil-lakshman updates the test for http error codes
=> dx 1415 drop isomorphic fetch and node fetch

sanity-report-dev11.js
=> dx 2069 sanity update

package-lock.json, package.json, sanity-report-dev11.js, sanity-report.js
removed cheerio package as it had high vulnerability in latest update
=> dx | 2117 | snyk issue | remove cheerio

CHANGELOG.md, README.md, index.d.ts, package-lock.json, package.json, sanity-report-dev11.js, sanity-report.js, src/core/contentstack.js, src/core/lib/utils.js
* update package files and changeLog
* updated change log
* update readme file
* Fixed license and semgrep issues
=> Back merge

.github/workflows/npm-publish.yml, CHANGELOG.md, README.md, index.d.ts, package-lock.json, package.json, sanity-report-dev11.js, src/core/contentstack.js
version: 3.24.2
update node22
license and semgrep issue
=> DX | 24-02-2025 | Release

CHANGELOG.md, index.d.ts, package-lock.json, package.json, src/core/contentstackregion.js, test/typescript/stack.test.ts
add support for GCP EU region in host configuration
=> feat: GCP-EU support

sanity-report-dev11.js
Updated the sanity suite name from "SDK-CDA" to "SDK-JS-CDA" in Slack notifications for better clarity.
- Updated suite name in sanity-report-dev11.js
- Verified Slack notification format
- No functional changes, only display text update
=> feat: update sanity suite name to SDK-JS-CDA
